# Generated by Django 4.2 on 2023-04-28 06:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="SK", max_length=2, verbose_name="Country"
            ),
        ),
    ]
